src/Entity/WeatherHistory.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WeatherHistoryRepository")
 */
class WeatherHistory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $latitude;

    /**
     * @ORM\Column(type="float")
     */
    private $longitude;

    /**
     * @ORM\Column(type="datetime")
     */
    private $added;

    /**
     * @ORM\Column(type="float")
     */
    private $temp;

    /**
     * @ORM\Column(type="integer")
     */
    private $pressure;

    /**
     * @ORM\Column(type="integer")
     */
    private $humidity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $visibility;

    /**
     * @ORM\Column(type="float")
     */
    private $wind_speed;

    /**
     * @ORM\Column(type="integer")
     */
    private $clouds;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $ip;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ua;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getAdded(): ?\DateTimeInterface
    {
        return $this->added;
    }

    public function setAdded(\DateTimeInterface $added): self
    {
        $this->added = $added;

        return $this;
    }

    public function getTemp(): ?float
    {
        return $this->temp;
    }

    public function setTemp(float $temp): self
    {
        $this->temp = $temp;

        return $this;
    }

    public function getPressure(): ?int
    {
        return $this->pressure;
    }

    public function setPressure(int $pressure): self
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(int $humidity): self
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getVisibility(): ?int
    {
        return $this->visibility;
    }

    public function setVisibility(int $visibility): self
    {
        $this->visibility = $visibility;

        return $this;
    }

    public function getWindSpeed(): ?float
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(float $wind_speed): self
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getClouds(): ?int
    {
        return $this->clouds;
    }

    public function setClouds(int $clouds): self
    {
        $this->clouds = $clouds;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUa(): ?string
    {
        return $this->ua;
    }

    public function setUa(?string $ua): self
    {
        $this->ua = $ua;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}Welcome!{% endblock %}</title>

        <link rel="stylesheet" href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}" >
        <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}" >

        <script src="{{ asset('assets/js/jquery-3.3.1.js') }}" ></script>

        <style>

            #mainMain {
                margin-top: 80px;
            }


        </style>

        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top111 bg-dark">
        <a class="navbar-brand" href="/">
            Map!
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/history">History </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/stats">Stats</a>
                </li>


            </ul>


            <form class="form-inline my-2 my-lg-0 d-none">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <main role="main" id="mainMain">

        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        {% block body %}{% endblock %}

    </main>



    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}" ></script>
    <script src="{{ asset('assets/js/main.js') }}" ></script>

        {% block javascripts %}{% endblock %}
    </body>




</html>

templates/history.html.twig
{% extends 'base.html.twig' %}

{% block title %}History{% endblock %}

{% block body %}

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">

                <h3>History</h3>

                <table class="table table-striped table-bordered table-hover">

                {% for data in pagination %}
                    <tr>
                        <td width="1%">
                            {{ data.id }}
                        </td>

                        <td>
                            {{ data.added|date("Y-m-d H:i") }}
                        </td>

                        <td>
                            {{ data.longitude }} / {{ data.latitude }}
                        </td>

                        <td>
                            {{ data.city }} ({{ data.country }})
                        </td>

                        <td>
                            {{ data.temp }}
                        </td>

                        <td>
                            {{ data.pressure }}
                        </td>

                        <td>
                            {{ data.humidity }}
                        </td>

                        <td>
                            {{ data.windspeed }}
                        </td>

                        <td>
                            {{ data.clouds }}
                        </td>

                        <td>
                            <a class="btn btn-info" href="/history/item/{{ data.id }}">more</a>
                        </td>

                    </tr>

                {% endfor %}

                </table>

                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>

            </div>

        </div>
    </div>



{% endblock %}

templates/history_item.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <h3>Item #{{ item.id }}</h3>

                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <td width="10%">
                           longitude/latitude
                        </td>
                        <td>
                            {{ item.longitude }}/{{ item.latitude }}
                        </td>

                    </tr>

                    <tr>
                        <td>
                            added
                        </td>
                        <td>
                            {{ item.added|date("Y-m-d H:i") }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            temp
                        </td>
                        <td>
                            {{ item.temp }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            description
                        </td>
                        <td>
                            {{ item.description }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            pressure
                        </td>
                        <td>
                            {{ item.pressure }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            humidity
                        </td>
                        <td>
                            {{ item.humidity }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            visibility
                        </td>
                        <td>
                            {{ item.visibility }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            wind_speed
                        </td>
                        <td>
                            {{ item.windSpeed }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            place
                        </td>
                        <td>
                            {{ item.city }}
                            {{ item.country }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            ip
                        </td>
                        <td>
                            {{ item.ip }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            ua
                        </td>
                        <td>
                            {{ item.ua }}
                        </td>
                    </tr>


                </table>

            </div>

        </div>
    </div>

{% endblock %}

templates/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12">

                <div class="text-center " id="mapSpinnerDiv">
                    <div id="mapSpinner" class="spinner-border text-success text-center " role="status" style="display: none"></div>
                </div>


                <div id="mainMap">

                    <div class="spinner-border text-success text-center" role="status"><span class="sr-only">Loading...</span></div>

                </div>

            </div>

        </div>
    </div>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0EGW4VTcGp9v95uv6uRj5kQCrE94u5Ek">
    </script>

    <div class="modal" tabindex="-1" role="dialog" id="mapResults">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Results</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        jQuery(document).ready(function () {
            setTimeout(initMap, 2000);
        });
    </script>

{% endblock %}

templates/modal.html.twig
<table class="table table-striped table-bordered table-hover">
    <tr>
        <td>
        City (Country)
        </td>
        <td>
            {{ data.name }}
            ({{ data.sys.country }})
        </td>
    </tr>

    <tr>
        <td>
            Weather
        </td>
        <td>
            {{ data.weather.0.description }}
        </td>
    </tr>



    <tr>
        <td>
        Temerature
        </td>
        <td>
            {{ data.main.temp }}
        </td>

    </tr>

    <tr>
        <td>
            Humidity
        </td>
        <td>
            {{ data.main.humidity }}
        </td>
    </tr>


    <tr>
        <td>
            Wind speed
        </td>
        <td>
            {{ data.wind.speed }}
        </td>
    </tr>


</table>



{#
{{ dump(data) }}
#}

templates/stats.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h1>Stats ({{ count }})</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            {% for c, data in aggregated %}
                {{ c }}:
                {{ data|number_format(2) }}
                <br>
            {% endfor %}
        </div>

        <div class="col-md-6">
            <div class="badge badge-primary">Popular searches</div>
            <br>
            {% for c, data in groupCity %}
                {{ data.city }}:
                {{ data.c }}
                <br>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}